#!/bin/bash

# ls
alias ls="ls --color=auto"
alias l="ls -FL"
alias ll="ls -Ahl"
alias la="ls -a"

# Clearing screen
alias c="echo -ne '\033c'"
alias cl="c;l"
alias cll="c;ll"
alias ccd="c;cd"

# Navigation
alias b="cd - >/dev/null && l" # b stands for back

# Interactive commands
alias mv="mv -i"  # "m" - never forget
alias cp="cp -i"

# Move up quickly
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .5="cd ../../../.."
alias .6="cd ../../../../.."
alias .7="cd ../../../../../.."
alias .8="cd ../../../../../../.."

# Shortcuts for installing
alias install='pacaur -S'
alias uninstall='pacaur -Rns'
alias update='pacaur -Syu'
alias autoremove='sudo pacman -Rns $(pacman -Qdtq)'

# Misc
alias e="exit"
alias eb="c; exec bash"

# CD
cd ()
{
    # Pass all arguments to cd
    builtin cd "$@"
    # Get return value
    RV=$?
    # If its not 0, just get out, it already printed message
    [ $RV = 0 ] || return $RV
    # If everything OK, print ls and todo
    l
    todo
}

# Prompt
source ~/.dotfiles/prompt
eval `dircolors`
