#!/bin/bash

# Declaration
warn() {
    echo Failed to $1
}

die() {
    warn "$1"
    exit 1
}

confirm() {
    warn "$1"
    echo -n "Do you want to continue? [y/n] "
    read -r value
    [ $value = "y.*" ] && return 1 || return 0
}

FILE_LOCATION=( "vim/vimrc" "bash_additions" "scripts" "i3/config" "i3/statusbar" "vim/UltiSnips" "Xresources" "todorc" "conky/primary" "conky/secondary" "compton" "rainbow-bash" "yabar" "dir_colors")
LINK_LOCATION=( ".vimrc" ".bash_additions" ".scripts" ".i3/config" ".i3blocks.conf" ".vim/UltiSnips" ".Xresources" ".todorc" ".conkyrc" ".conkyrc2" ".compton.conf" ".rainbow-bash" ".config/yabar/yabar.conf" ".dir_colors" )
AMOUNT_FILES=${#LINK_LOCATION[@]}
(( AMOUNT_FILES-- ))
PREFIX=~/.dotfiles/

# Action
cd ~ || die "cd to ~"
mv dotfiles .dotfiles || {
    if ! confirm "move dotfiles to .dotfiles"; then
        echo "Aborting."
        exit 1
    fi
}

for i in `seq 0 $AMOUNT_FILES`; do
    file="$PREFIX${FILE_LOCATION[$i]}"
    link="${LINK_LOCATION[$i]}"
    ln -n -s -f "$file" "$link" || warn "create link from $link to $file"
    # -f = replace existing, -n = treat as normal if its a directory
done

cat >>.bashrc <<EOF || die "change .bashrc"

source ~/.dotfiles/bash_additions/all
RBW_PATH=\$HOME/.rainbow-bash
source \$RBW_PATH/init.sh
rbw_load_theme personal
c # In bash_additions/all -> scripts, we cd twice, clear that shit
EOF

echo "Success!"
