#!/bin/bash

# Declaration
warn() {
    echo Failed to $1
}

die() {
    warn "$1"
    exit 1
}

confirm() {
    warn "$1"
    echo -n "Do you want to continue? [y/n] "
    read -r value
    [ $value = "y.*" ] && return 1 || return 0
}

FILE_LOCATION=( "vim/vimrc" "scripts" "i3/config" "vim/UltiSnips" "Xresources" "todorc" "conky" "compton" "polybar" "dir_colors" "zshrc" )
LINK_LOCATION=( ".vimrc" ".scripts" ".i3/config" ".vim/UltiSnips" ".Xresources" ".todorc" ".conkyrc" ".compton.conf" ".config/polybar/config" ".dir_colors" ".zshrc" )
AMOUNT_FILES=${#LINK_LOCATION[@]}
(( AMOUNT_FILES-- ))
PREFIX=~/.dotfiles/

# Action
cd ~ || die "cd to ~"
mv dotfiles .dotfiles || {
    if ! confirm "move dotfiles to .dotfiles"; then
        echo "Aborting."
        exit 1
    fi
}

for i in `seq 0 $AMOUNT_FILES`; do
    file="$PREFIX${FILE_LOCATION[$i]}"
    link="${LINK_LOCATION[$i]}"
    ln -n -s -f "$file" "$link" || warn "create link from $link to $file"
    # -f = replace existing, -n = treat as normal if its a directory
done

echo "Success!"
