#!/bin/bash

# Get interface
IF=wlo1
# Check if down, if it is, then display "down"
if [[ "$(cat /sys/class/net/$IF/operstate)" = 'down' ]]; then
  echo No I-net
  exit
fi

ans=`ping 8.8.8.8 -c 1 2>/dev/null | head -n 2`

if (( $? == 0 )); then
    ans=`echo $ans | head -n 2 | tail -n 1 | cut -d '=' -f 4`
else
    echo 0ms
    exit
fi

echo $ans
