#!/bin/bash

cd ()
{
    # Pass all arguments to cd
    builtin cd "$@"
    # Get return value
    RV=$?
    # If its not 0, just get out, it already printed message
    [ $RV = 0 ] || return $RV
    # If everything OK, print ls and todo
    l
    todo
}
