#!/bin/bash

USERNAME=6
PATH_COLOR=0

GOOD_EXIT_STATUS=2
BAD_EXIT_STATUS=1

REGULAR_USER=4
ROOT_USER=1

COMMAND_TEXT_BG=0

_transition ()
{
    echo -n '\['
    tput sgr0
    tput setab $2
    tput setaf $1
    echo -n '\]'
    echo -n $'\uE0B0'
    echo -n '\['
    tput setab $2
    echo -n '\]'
}


_display_base ()
{
    echo -n "\\[$(tput setaf 7; tput bold; tput setab $USERNAME)\\]$USER$(_transition $USERNAME $PATH_COLOR)"
}


_display_shorter_path()
{
    # Change /home/amit to ~, only do last 3 dirs
    DIR=`pwd | sed "s#$HOME#\~#g" | rev | cut -d '/' -f '-3' | rev`

    echo "\\[$(tput setaf 7; tput bold)\\]$DIR"
}


_display_exit_status()
{
    RV=$? # Get return value of last command

    (( $RV == 0 )) && color=$GOOD_EXIT_STATUS || color=$BAD_EXIT_STATUS

    echo "\\[$(tput setab $color; tput bold)\\][$RV]$(_transition $color $USERNAME)"
}


_display_prompt_end ()
{
    if [ "$(id -u)" != "0" ]; then
        end="$"
        color=$REGULAR_USER
    else
        end=$'\u2622'
        color=$ROOT_USER
    fi

    echo -n "$(_transition $PATH_COLOR $color)\\[$(tput setaf 7; tput bold)\\]$end"

    _transition $color $COMMAND_TEXT_BG

    echo -n "\\[$(tput sgr0)\\] "
}


_update_ps1 ()
{
    PS1="$(_display_exit_status)$(_display_base)$(_display_shorter_path)$(_display_prompt_end)"
}

PROMPT_COMMAND="_update_ps1"
