[vim.files]
vimrc = "~/AppData/Local/nvim/init.vim"
coc_settings = "~/AppData/Local/nvim/coc-settings.json"

[bash.files.zprofile]
target = "~/.bash_profile"
type = "template"
prepend = """
if [ `pwd` = /c/WINDOWS/system32 ]; then
    builtin cd ~/Desktop
fi
. ~/.bashrc
"""
