#!/usr/bin/env zsh

numlockx
setxkbmap -layout us,il -option grp:alt_shift_toggle
~/bin/clean_tmp
~/.fehbg

xrdb ~/.Xresources &
conky &
conky -c ~/.conkyrc2 &
/usr/bin/compton &
pulseaudio --start &
xfce4-power-manager &
dunst &

disown -a
