#!/bin/bash

directory=~/usr/archive/img/background

trap true SIGTERM

files=$(ls $directory | sort -R)
while true; do
    for file in $files; do
        feh --bg-scale $directory/$file
        sleep 300 &
        wait
        kill %1
    done
done
