[helpers]
color_rgb = ".dotter/helpers/color_rgb.rhai"

[i3]
depends = ["graphics"]

[i3.files]
# Local variables: network_interface, screen_size, terminal, primary_screen, secondary_screen
# Optional local variables: owo_key
dunstrc = "~/.config/dunst/dunstrc"
rofi = "~/.config/rofi/config.rasi"
compton = "~/.compton.conf"
conky = "~/.conkyrc"
i3 = "~/.i3/config"
polybar = "~/.config/polybar/config"

[i3.variables]
# Rofi
rofi_font_size = 20
rofi_padding = 200
# Conky
conky_graph_gap = 20
conky_graph_height = 40
conky_width = 250
battery_uevent = "/sys/class/power_supply/BAT0/uevent"

[shell.files]
# Optional local variables: email+git_username
tmux = "~/.tmux.conf"
scripts = "~/.scripts"
dir_colors = "~/.dir_colors"
git = "~/.gitconfig"
git_prompt = "~/.git_prompt"
bat = "~/.config/bat/config"
ripgrep = { type = "symbolic", target = "~/.ripgreprc", if = '(is_executable "rg")'}
"atuin.toml" = { type = "symbolic", target = "~/.config/atuin/config.toml", if = '(is_executable "atuin")'}

[shell.variables]
# Local variables: install, uninstall, update, autoremove, user_color
install = "echo not defined"
uninstall = "echo not defined"
update = "echo not defined"
autoremove = "echo not defined"
user_color = "7"

[zsh]
depends = ["shell"]

[zsh.files]
# conflicts with "bash"
zprofile = "~/.zprofile"
zshrc = "~/.zshrc"

[bash]
depends = ["shell"]

[bash.files]
# conflicts with "zsh"
zprofile = "~/.bash_profile"
zshrc = "~/.bashrc"
minttyrc = "" # overridden in include/windows.toml

[cargo.files]
cargo = "~/.cargo/config.toml"

[termite]
depends = ["graphics"]

[termite.files]
termite = "~/.config/termite/config"

[xfce4_terminal]
depends = ["graphics"]

[xfce4_terminal.files]
xfce4_terminal = "~/.config/xfce4/terminal/terminalrc"
xfce4_terminal_accels = "~/.config/xfce4/terminal/accels.scm"

[vim.files]
# Optional local variables: arm
nvim = "~/.config/nvim"

[graphics.variables.colors]
background = "222222"
background_alt = "444444"
background_bright = "666666"
text_muted = "666666"
text = "dedede"
text_bright = "ffffff"
accent = "bd2c40"

[graphics.variables.colors16]
background   = "151515"
foreground   = "d7d0c7"
cursor       = "d7d0c7"
# In terminal color index order
black        = "101010"
red          = "e84f4f"
green        = "b8d68c"
yellow       = "e1aa5d"
blue         = "7dc1cf"
purple       = "9b64fb"
cyan         = "6d878d"
light_gray   = "dddddd"
dark_gray    = "404040"
light_red    = "d23d3d"
light_green  = "a0cf5d"
light_yellow = "f39d21"
light_blue   = "4e9fb1"
light_purple = "8542ff"
light_cyan   = "42717b"
white        = "dddddd"

[graphics.variables.font]
regular = "Ubuntu"
monospace = "Fira Code"
size = 12
