Xinitrc = "~/.xinitrc"
Xresources = "~/.Xresources"
compton = "~/.compton.conf"
conky = "~/.conkyrc"
dir_colors = "~/.dir_colors"
dunstrc = "~/.config/dunst/dunstrc"
herbstluft = "~/.config/herbstluftwm/autostart"
i3 = "~/.i3/config"
polybar = "~/.config/polybar/config"
scripts = "~/.scripts"
termite = "~/.config/termite/config"
tmux = "~/.tmux.conf"
todorc = "~/.todorc"
tonky = "~/.conkyrc2"
"vim/UltiSnips" = "~/.vim/UltiSnips"
"vim/pythonx" = "~/.vim/pythonx"
"vim/vimrc" = "~/.config/nvim/init.vim"
xfce4_terminal = "~/.config/xfce4/terminal/terminalrc"
zprofile = "~/.zprofile"
zshrc = "~/.zshrc"
