[helpers]
color_rgb = "dotter_settings/helpers/color_rgb.rhai"

[i3.files]
# requires "graphics"
# Local variables: network_interface, screen_size, terminal, primary_screen, secondary_screen
dunstrc = "~/.config/dunst/dunstrc"
rofi = "~/.config/rofi/config.rasi"
compton = "~/.compton.conf"
conky = "~/.conkyrc"
i3 = "~/.i3/config"
polybar = "~/.config/polybar/config"
tonky = "~/.conkyrc2"

[i3.variables]
# Rofi
rofi_font_size = 20
rofi_padding = 200
# Conky
conky_graph_gap = 20
conky_graph_height = 40
conky_width = 250
battery_uevent = "/sys/class/power_supply/BAT0/uevent"

[shell.files]
# Optional local variables: load_rc, cd_location, email+git_username, delta
todorc = "~/.todorc"
tmux = "~/.tmux.conf"
scripts = "~/.scripts"
dir_colors = "~/.dir_colors"
git = "~/.gitconfig"

[shell.variables]
install = "echo not defined"
uninstall = "echo not defined"
update = "echo not defined"
autoremove = "echo not defined"

[zsh.files]
# requires "shell", conflicts with "bash"
# Local variables: install, uninstall, update, autoremove
zprofile = "~/.zprofile"
zshrc = "~/.zshrc"

[zsh.variables]
zsh = true

[bash.files]
# requires "shell", conflicts with "zsh"
# Local variables: install, uninstall, update, autoremove
zprofile = "~/.bash_profile"
zshrc = "~/.bashrc"

[bash.variables]
zsh = false

[termite.files]
# requires "graphics"
termite = "~/.config/termite/config"

[xfce4_terminal.files]
# requires "graphics"
xfce4_terminal = "~/.config/xfce4/terminal/terminalrc"
xfce4_terminal_accels = "~/.config/xfce4/terminal/accels.scm"

[vim.files]
vimrc = "~/.config/nvim/init.vim"

[graphics.variables.colors]
background = "222222"
background_alt = "444444"
background_bright = "666666"
text_muted = "666666"
text = "dedede"
text_bright = "ffffff"
accent = "bd2c40"

[graphics.variables.colors16]
# In terminal color index order
black        = "000000"
red          = "fb3029"
green        = "00cd00"
yellow       = "cdcd00"
blue         = "0000cd"
purple       = "cd00cd"
cyan         = "00cdcd"
light_gray   = "e5e5e5"
dark_gray    = "7f7f7f"
light_red    = "ff0000"
light_green  = "00ff00"
light_yellow = "ffff00"
light_blue   = "5c5cff"
light_purple = "ff00ff"
light_cyan   = "00ffff"
white        = "ffffff"

[graphics.variables.font]
regular = "Ubuntu"
monospace = "Fira Mono"
size = 12
