[helpers]
color_rgb = "dotter_settings/helpers/color_rgb.rhai"

[i3.files]  # requires "graphics"
dunstrc = "~/.config/dunst/dunstrc"
Xinitrc = "~/.xinitrc"
Xresources = "~/.Xresources"  # rofi
compton = "~/.compton.conf"
conky = "~/.conkyrc"
i3 = "~/.i3/config"
polybar = "~/.config/polybar/config"
tonky = "~/.conkyrc2"
# Local variables: network_interface, screen_size, terminal,

[i3.variables]
# Rofi
rofi_font_size = 20
rofi_padding = 200

# Conky
conky_graph_gap = 20
conky_graph_height = 40
conky_width = 250
battery_uevent = "/sys/class/power_supply/BAT0/uevent"

[zsh.files]
zprofile = "~/.zprofile"
zshrc = "~/.zshrc"
todorc = "~/.todorc"
tmux = "~/.tmux.conf"
scripts = "~/.scripts"
dir_colors = "~/.dir_colors"
# Local variables: install, uninstall, update, autoremove

[termite.files]  # requires "graphics"
termite = "~/.config/termite/config"

[xfce4_terminal.files]  # Doesn't require "graphics" but should
xfce4_terminal = "~/.config/xfce4/terminal/terminalrc"

[vim.files]
vimrc = "~/.config/nvim/init.vim"

[graphics.variables]
color_background = "#1b1b1b"
color_black = "#1b1b1b"
color_blue = "#6a9fb5"
color_cyan = "#75b5aa"
color_dark_gray = "#262626"
color_foreground = "#dedede"
color_green = "#90a959"
color_light_blue = "#2a5e74"
color_light_cyan = "#297366"
color_light_gray = "#616161"
color_light_green = "#5d742a"
color_light_purple = "#703664"
color_light_red = "#752a2a"
color_light_yellow = "#754e2a"
color_purple = "#aa759f"
color_red = "#ac4142"
color_white = "#9e9e9e"
color_yellow = "#f4bf75"
monofont = "Fira Mono"
regfont = "Ubuntu"
fontsize = 12
