color_background = "#1b1b1b"
color_black = "#1b1b1b"
color_blue = "#6a9fb5"
color_cyan = "#75b5aa"
color_dark_gray = "#262626"
color_foreground = "#dedede"
color_green = "#90a959"
color_light_blue = "#2a5e74"
color_light_cyan = "#297366"
color_light_gray = "#616161"
color_light_green = "#5d742a"
color_light_purple = "#703664"
color_light_red = "#752a2a"
color_light_yellow = "#754e2a"
color_purple = "#aa759f"
color_red = "#ac4142"
color_white = "#9e9e9e"
color_yellow = "#f4bf75"
email = "me@amitgold.com"
fontsize = "10"
full_name = "Amit Gold"
github = "https://www.github.com/SuperCuber"
monofont = "Fira Mono"
regfont = "Ubuntu"
terminal = "xfce4-terminal"
